version: "3.3"

services:
  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    volumes:
      - /docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=*****
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=*****

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud:latest
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
    volumes:
      - /docker/nextcloud/html:/var/www/html
      - /mnt/nas/nextcloud:/var/www/html/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=*****
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - REDIS_HOST=redis
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: always
    ports:
      - "9980:9980"
    environment:
      - domain=cloud\\.local\\.com # Use the actual domain of your Nextcloud, double escaped
      - username=admin
      - password=********
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    cap_add:
      - MKNOD
