version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-paper
    environment:
      # CF_API_KEY: ${CF_API_KEY} # For mods
      # CF_PAGE_URL: ${CF_PAGE_URL} # For mods
      SERVER_NAME: ${SERVER_NAME}
      EULA: "true"
      TYPE: PAPER
      # MOD_PLATFORM: AUTO_CURSEFORGE # For mods
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      MEMORY: ${MEMORY}
      DIFFICULTY: ${DIFFICULTY}
      OPS: ${OPS}
      WHITELIST: ${WHITELIST}
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      SEED: ${SEED}
      PVP: true
    ports:
      - 25565:25565 # MINCRAFT
      - 25575:25575 # RCON
    volumes:
      - /docker/mc-paper:/data
    restart: unless-stopped
