version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole

    restart: unless-stopped
    #cap_add:
    #- NET_ADMIN

    # Network only needed if you want to use pihole while connected to the WireGuard VPN.
    networks:
      wireguard-pihole:
        ipv4_address: 172.20.0.2
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 67:67/udp
      # Ports 80 and 443 changed to avoid conflict with NginxProxyManager
      - 8080:80/tcp
      - 4443:443/tcp
      # Volumes set up as root for Proxmox default
    volumes:
      - /root/pihole/etc:/etc/pihole
      - /root/pihole/dns:/etc/dnsmasq.d
    environment:
      - TZ=America/Chicago
      - WEBPASSWORD=changeme

# Network only needed if you want to use pihole while connected to the WireGuard VPN.
networks:
  wireguard-pihole:
    name: "wireguard-pihole"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
