version: '3'

services:
  # Indexer
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /root/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: always
  # Books
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /root/readarr/data:/config
      - /mnt/nas/media/books:/books #optional
      - /mnt/nas/media/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: always
  # Shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /root/sonarr/data:/config
      - /mnt/nas/media/tv:/tv #optional
      - /mnt/nas/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: always
  # Movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /root/radarr/data:/config
      - /mnt/nas/media/movies:/movies #optional
      - /mnt/nas/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: always
  # Command and control
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=America/Chicago
       ports:
            - 5055:5055
       volumes:
            - /root/jellyseerr/config:/app/config
       restart: always
  # Torrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /root/qbittorrent/config:/config
      - /mnt/nas/media/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always