version: "3.2"
services:
  # Indexer
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: always
  # Books
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/readarr/:/config
      - /mnt/nas/media/data/media/books:/books #optional
    ports:
      - 8787:8787
    restart: always
  # Movies
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /mnt/nas/media/data/media:/data
  # TV Shows
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /mnt/nas/media/data/media:/data
  # Subtitles
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /mnt/nas/media/data/media:/data/media
  # News
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 8081:8081
      - 9090:9090
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /mnt/nas/media/data/usenet/usenet:/data/usenet:rw
  # Command and control
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/jellyseerr/config:/app/config
    restart: always
  # Torrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/appdata/qbittorrent/config:/config
      - /mnt/nas/media/data/torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
