version: "3.8"

services:
  valheim-server:
    image: ghcr.io/lloesche/valheim-server
    container_name: valheim-server
    cap_add:
      - sys_nice
    stop_grace_period: 2m
    ports:
      - 2456-2457:2456-2457/udp
    volumes:
      - /docker/valheim-server/config:/config
      - /docker/valheim-server/data:/opt/valheim
    environment:
      - SERVER_NAME=${NAME}
      - WORLD_NAME=${WORLD}
      - SERVER_PASS=${PASSWORD}
      - SERVER_PUBLIC=false
      - PUBLIC_TEST=true
      - BACKUPS_CRON="0 */12 * * *"
      - STATUS_HTTP=true
      - SERVER_ARGS="-crossplay"
      - DISCORD_WEBHOOK=${WEBHOOK_URL}
      - DISCORD_MESSAGE_START="Valheim server $$SERVER_NAME is starting."
      - DISCORD_MESSAGE_RESTART="Valheim server $$SERVER_NAME is restarting."
      - 'PRE_BOOTSTRAP_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_MESSAGE_START)\"}" "$$DISCORD_WEBHOOK"'
      - 'PRE_RESTART_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$(eval echo $$DISCORD_MESSAGE_RESTART)\"}" "$$DISCORD_WEBHOOK"'
