version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    ports:
      - "${PORT}:${PORT}/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: ${PORT}
      NAME: "${NAME}"
      WORLD: "${WORLD}"
      PASSWORD: "${PASSWORD}"
      TZ: "${TZ}"
      ENABLE_CROSSPLAY: 1
      PUBLIC: 0
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 5 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "0 3 * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 5
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      WEBHOOK_URL: "${WEBHOOK_URL}"
      WEBHOOK_INCLUDE_PUBLIC_IP: 0
      UPDATE_ON_STARTUP: 0
      STEAMCMD_ARGS: ${STEAMCMD_ARGS} # Used to play beta versions as well
    volumes:
      - /docker/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /docker/valheim/server:/home/steam/valheim
      - /docker/valheim/backups:/home/steam/backups
